Repository FalkenDev/TrainControllerJS, pull requests merged in 2023-10, with the labels that each got.

#39 Fixed various issues related auth
  frontend/src/components/AuthModal.vue
Labels: codeFix

#41 Refactor to only use GraphQL
  backend/index.js
  backend/v1/controllers/auth.js
  backend/v1/controllers/stations.js
  backend/v1/controllers/trains.js
  backend/v1/graphQL/resolvers.js
  backend/v1/graphQL/typeDefs.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DeleteDialog.vue
  frontend/src/components/EditDialog.vue
  frontend/src/components/Home.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/main.js
  frontend/src/models/auth.js
  frontend/src/models/trains.js
Labels: enhancement, codeFix

#47 GraphQL - Implemented tests to test the functions but also resolvers and typeDefs
  backend/package-lock.json
  backend/package.json
  backend/v1/graphQL/resolvers.js
  backend/v1/tests/graphQL.test.js
Labels: enhancement, Tests

#48 Refactor to use 2 CI frontend & backend
  .github/workflows/nodeBackend.js.yml
  .github/workflows/nodeFrontend.js.yml
Labels: Tests

#54 bugfix
  frontend/src/components/Home.vue
  frontend/src/components/TripList.vue
Labels: codeFix

#56 Kmom05-09
  .github/workflows/cypressFrontend.yml
  .github/workflows/nodeBackend.js.yml
  .github/workflows/nodeFrontend.js.yml
  .gitignore
  backend/.gitignore
  backend/.idea/.gitignore
  backend/.idea/backend.iml
  backend/.idea/modules.xml
  backend/.idea/vcs.xml
  backend/db/trains.sqlite
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/v1/controllers/auth.js
  backend/v1/controllers/stations.js
  backend/v1/controllers/trains.js
  backend/v1/graphQL/resolvers.js
  backend/v1/graphQL/typeDefs.js
  backend/v1/index.js
  backend/v1/models/User.js
  backend/v1/routes/auth.js
  backend/v1/sockets/ticketHandling.js
  backend/v1/sockets/trainHandling.js
  backend/v1/tests/auth.test.js
  backend/v1/tests/graphQL.test.js
  backend/v1/tests/socket.test.js
  frontend/.gitignore
  frontend/cypress.config.js
  frontend/cypress/e2e/home.cy.js
  frontend/cypress/fixtures/example.json
  frontend/cypress/intergration/Home.spec.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/train.svg
  frontend/src/App.vue
  frontend/src/assets/marker.svg
  frontend/src/components/AuthModal.vue
  frontend/src/components/AuthProvider.vue
  frontend/src/components/DeleteDialog.vue
  frontend/src/components/EditDialog.vue
  frontend/src/components/Filter.vue
  frontend/src/components/Header.vue
  frontend/src/components/Home.vue
  frontend/src/components/Map.vue
  frontend/src/components/SelectProvider.vue
  frontend/src/components/TrainCard.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/components/TripList.vue
  frontend/src/main.js
  frontend/src/mockData/data.js
  frontend/src/models/auth.js
  frontend/src/models/trains.js
  frontend/src/tests/Home.spec.js
  package-lock.json
Labels: enhancement
