Repository FalkenDev/TrainControllerJS, pull requests merged in 2023-09, with the labels that each got.

#8 Create node.js.yml
  .github/workflows/node.js.yml
Labels: Tests

#6 New Backend Setup with MongoDB
  .vscode/settings.json
  backend/.env.config
  backend/.gitignore
  backend/Dockerfile
  backend/LICENSE
  backend/app.js
  backend/db/database.js
  backend/db/migrate.sql
  backend/db/reset_db.bash
  backend/index.js
  backend/models/codes.js
  backend/models/delayed.js
  backend/models/tickets.js
  backend/models/trains.js
  backend/models/utils.js
  backend/package-lock.json
  backend/package.json
  backend/routes/codes.js
  backend/routes/delayed.js
  backend/routes/tickets.js
  backend/v1/controllers/trains.js
  backend/v1/documentation/documentation.html
  backend/v1/documentation/style.css
  backend/v1/index.js
  backend/v1/models/TrainTickets.js
  backend/v1/routes/auth.js
  backend/v1/routes/trains.js
  backend/v1/routes/users.js
Labels: enhancement

#9 Workflow Update
  .github/workflows/node.js.yml
Labels: Tests

#11 FIxed to work with azure
  backend/index.js
  backend/package.json
  backend/v1/routes/trains.js
Labels: codeFix

#13 Trainlist & Websocket
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Home.vue
  frontend/src/components/Map.vue
  frontend/src/components/TrainCard.vue
  frontend/src/components/TripList.vue
  frontend/src/models/trains.js
Labels: enhancement

#14 Sidebar
  frontend/src/components/Home.vue
  frontend/src/components/Map.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/components/TripList.vue
  frontend/src/models/trains.js
Labels: enhancement

#15 CORS ip's to env
  backend/index.js
Labels: codeFix

#17 Sidebar functionality
  frontend/src/App.vue
  frontend/src/components/Home.vue
  frontend/src/components/TrainCard.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/main.js
  frontend/src/models/trains.js
Labels: enhancement

#18 Added train icons to the frontend
  frontend/src/assets/trainLogos/NRail.png
  frontend/src/assets/trainLogos/SLL.png
  frontend/src/assets/trainLogos/blsrail.png
  frontend/src/assets/trainLogos/jlt.png
  frontend/src/assets/trainLogos/malab.png
  frontend/src/assets/trainLogos/malartag.svg
  frontend/src/assets/trainLogos/mtab.png
  frontend/src/assets/trainLogos/mtrx.png
  frontend/src/assets/trainLogos/otog.png
  frontend/src/assets/trainLogos/sj.png
  frontend/src/assets/trainLogos/skanetrafiken.png
  frontend/src/assets/trainLogos/togab.png
  frontend/src/assets/trainLogos/vast.png
  frontend/src/assets/trainLogos/vy.png
  frontend/src/components/TrainCard.vue
Labels: enhancement

#20 Fixed adding and removing tickets
  frontend/src/components/Home.vue
  frontend/src/components/TrainCard.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/models/trains.js
  frontend/src/tests/Home.spec.js
Labels: codeFix

#16 GraphQL Implementation Week 5-9
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/v1/graphQL/resolvers.js
  backend/v1/graphQL/typeDefs.js
Labels: enhancement

#26 Ticket sockets Backend and Frontend
  backend/index.js
  backend/v1/controllers/trains.js
  backend/v1/sockets/ticketHandling.js
  backend/v1/sockets/trainHandling.js
  frontend/src/components/Home.vue
  frontend/src/components/Map.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/components/TripList.vue
Labels: enhancement

#27 Routed the api to azure
  frontend/src/components/Home.vue
Labels: codeFix

#29 Frontend Socket implementation and fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DeleteDialog.vue
  frontend/src/components/EditDialog.vue
  frontend/src/components/Home.vue
  frontend/src/components/TrainDetails.vue
  frontend/src/components/TripList.vue
  frontend/src/models/trains.js
Labels: enhancement, codeFix

#31 Filter and map update | Frontend
  backend/v1/sockets/trainHandling.js
  frontend/src/assets/marker.svg
  frontend/src/components/Filter.vue
  frontend/src/components/Home.vue
  frontend/src/components/Map.vue
  frontend/src/components/TrainCard.vue
  frontend/src/components/TripList.vue
Labels: bug, enhancement, codeFix

#33 Switch back to use azure
  frontend/src/components/Home.vue
Labels: codeFix

#36 Filter map trains
  .gitignore
  backend/.gitignore
  frontend/.gitignore
  frontend/src/components/Filter.vue
  frontend/src/components/Header.vue
  frontend/src/components/Home.vue
  frontend/src/components/Map.vue
  frontend/src/components/TripList.vue
Labels: enhancement, codeFix
